In [1]:
import pandas as pd

## First Dataset for EVs
This dataset shows the make, model year, EV type, range, and retail price

In [17]:
# Showing columns 5-8 & 10-11
ev_df = pd.read_csv("Data/ev_pop.csv")[["Model Year", "Make", "Electric Vehicle Type", "Electric Range", "Base MSRP"]]
ev_df.head(90)

,Model Year,Make,Electric Vehicle Type,Electric Range,Base MSRP
0,2019,Audi,Battery Electric Vehicle (BEV),204,74800.0
1,2017,Nissan,Battery Electric Vehicle (BEV),107,30680.0
2,2016,Nissan,Battery Electric Vehicle (BEV),84,29010.0
3,2018,BMW,Battery Electric Vehicle (BEV),114,44450.0
4,2016,Nissan,Battery Electric Vehicle (BEV),84,29010.0
...,...,...,...,...,...
85,2013,Nissan,Battery Electric Vehicle (BEV),75,28800.0
86,2015,Nissan,Battery Electric Vehicle (BEV),84,29010.0
87,2019,Chevrolet,Plug-in Hybrid Electric Vehicle (PHEV),53,33520.0
88,2013,Nissan,Battery Electric Vehicle (BEV),75,28800.0
89,2018,Tesla,Battery Electric Vehicle (BEV),215,36000.0

In [55]:
# Dropping all rows that are plug-in hybrids
def no_plug_ins(df):
    plug_ins = df.loc[df["Electric Vehicle Type"] == "Plug-in Hybrid Electric Vehicle (PHEV)"].index
    [plug_ins.astype(int) for x in plug_ins]
    df.drop(index=plug_ins, inplace=True)
    
no_plug_ins(ev_df)

In [56]:
ev_df.head(90)

,Model Year,Make,Electric Vehicle Type,Electric Range,Base MSRP
0,2019,Audi,Battery Electric Vehicle (BEV),204,74800.0
1,2017,Nissan,Battery Electric Vehicle (BEV),107,30680.0
2,2016,Nissan,Battery Electric Vehicle (BEV),84,29010.0
3,2018,BMW,Battery Electric Vehicle (BEV),114,44450.0
4,2016,Nissan,Battery Electric Vehicle (BEV),84,29010.0
...,...,...,...,...,...
116,2016,Tesla,Battery Electric Vehicle (BEV),200,74000.0
117,2018,Chevrolet,Battery Electric Vehicle (BEV),238,37495.0
118,2012,Nissan,Battery Electric Vehicle (BEV),73,35200.0
119,2017,Chevrolet,Battery Electric Vehicle (BEV),238,37495.0
120,2015,Tesla,Battery Electric Vehicle (BEV),208,69900.0

## Second Dataset for EVs
Shows the manufacturer, model, model year, Fuel, and category

In [35]:
ev_df2 = pd.read_csv("Data/vehicles.csv")[["Model", "Model Year", "Manufacturer", "Fuel", "Category"]]
ev_df2.head(90)

                  Model Model Year       Manufacturer      Fuel     Category
0                i3 BEV       2017                BMW  Electric  Sedan/Wagon
1                i3 BEV       2017                BMW  Electric  Sedan/Wagon
2                  Bolt       2017          Chevrolet  Electric  Sedan/Wagon
3                  500e       2017               Fiat  Electric  Sedan/Wagon
4                 Ioniq       2017            Hyundai  Electric  Sedan/Wagon
..                  ...        ...                ...       ...          ...
85             EV1-NiMH       2001  General Motors EV  Electric  Sedan/Wagon
86             Altra EV       2001             Nissan  Electric  Sedan/Wagon
87  Hypermini (CA only)       2001             Nissan  Electric  Sedan/Wagon
88              Citivan       2001          Solectria  Electric          Van
89                Flash       2001          Solectria  Electric        Truck

[90 rows x 5 columns]

In [82]:
ev_df2.loc[ev_df2.Manufacturer == "Tesla"]

               Model Model Year Manufacturer      Fuel     Category
7            Model S       2017        Tesla  Electric  Sedan/Wagon
17           Model S       2016        Tesla  Electric  Sedan/Wagon
18       Model S AWD       2016        Tesla  Electric  Sedan/Wagon
19   Model X AWD 90D       2016        Tesla  Electric          SUV
20  Model X AWD P90D       2016        Tesla  Electric          SUV
31           Model S       2015        Tesla  Electric  Sedan/Wagon
44           Model S       2014        Tesla  Electric  Sedan/Wagon
54           Model S       2013        Tesla  Electric  Sedan/Wagon

## First Dataset for gasoline
Shows the make and model of the vehicle, mpg for city and highway, class, and retail price

In [118]:
gas_df = pd.read_csv("Data/cars.csv")[["Unnamed: 0", "Retail", "CityMPG", "HighwayMPG", "Class"]]
gas_df = ev_df3.rename(columns={"Unnamed: 0": "Model"})
gas_df.head()

                     Model  Retail  CityMPG  HighwayMPG   Class
0             Acura 3.5 RL   43755       18          24   Sedan
1  Acura 3.5 RL Navigation   46100       18          24   Sedan
2                Acura MDX   36945       17          23     SUV
3              Acura NSX S   89765       17          24  Sports
4                Acura RSX   23820       24          31   Sedan

## Seocond Dataset for gasoline
Shows fuel type, make, model, and year

In [120]:
gas_df2 = pd.read_csv("Data/vehicles-2.csv")[["fuelType1", "make", "model", "year"]]

# Dropping all cars that are made before 2010
gas_df2 = gas_df2.loc[gas_df2.year > 2012]

# Dropping all columns that are electric
gas_df2 = gas_df2.loc[gas_df2.fuelType1 != "Electricity"]

gas_df2.head(90)

              fuelType1        make           model  year
24395  Premium Gasoline      Nissan            GT-R  2013
24396  Premium Gasoline  Volkswagen              CC  2013
24397  Premium Gasoline  Volkswagen              CC  2013
24398  Premium Gasoline  Volkswagen      CC 4motion  2013
24399  Regular Gasoline   Chevrolet  Malibu eAssist  2013
...                 ...         ...             ...   ...
24551  Premium Gasoline         BMW    X6 xDrive50i  2013
24552  Regular Gasoline       Lexus      RX 350 AWD  2013
24554  Premium Gasoline       Lexus     RX 450h AWD  2013
24555  Premium Gasoline         BMW    X5 xDrive35i  2013
24556  Premium Gasoline         BMW            X5 M  2013

[90 rows x 4 columns]

In [190]:
import requests
import json

In [191]:
gas = requests.get("https://vpic.nhtsa.dot.gov/api/vehicles/getmanufacturerdetails/honda?format=json")

In [192]:
gas = gas.json() # Dictionary
gas

{'Count': 13,
 'Message': 'Response returned successfully',
 'SearchCriteria': None,
 'Results': [{'Address': '2-1-1 Minami-Aoyama, Minato-ku',
   'Address2': None,
   'City': 'Tokyo',
   'ContactEmail': 'Unknown@unknown.com',
   'ContactFax': None,
   'ContactPhone': None,
   'Country': 'JAPAN',
   'DBAs': None,
   'EquipmentItems': [],
   'LastUpdated': '/Date(1441217874880-0400)/',
   'ManufacturerTypes': [],
   'Mfr_CommonName': 'Honda',
   'Mfr_ID': 987,
   'Mfr_Name': 'HONDA MOTOR CO., LTD',
   'OtherManufacturerDetails': 'Truck is another product.',
   'PostalCode': '107-8556',
   'PrimaryProduct': None,
   'PrincipalFirstName': 'Koichi Kondo',
   'PrincipalLastName': None,
   'PrincipalPosition': 'CEO',
   'StateProvince': 'Musashi',
   'SubmittedName': None,
   'SubmittedOn': None,
   'SubmittedPosition': None,
   'VehicleTypes': []},
  {'Address': '1919 TORRANCE BLVD',
   'Address2': None,
   'City': 'Torrance',
   'ContactEmail': None,
   'ContactFax': None,
   'ContactPhone': None,
   'Country': 'UNITED STATES (USA)',
   'DBAs': None,
   'EquipmentItems': [],
   'LastUpdated': '/Date(-2208970800000-0500)/',
   'ManufacturerTypes': [],
   'Mfr_CommonName': 'Honda',
   'Mfr_ID': 988,
   'Mfr_Name': 'HONDA OF AMERICA MFG., INC.',
   'OtherManufacturerDetails': 'Truck is another product',
   'PostalCode': '90501-2746',
   'PrimaryProduct': None,
   'PrincipalFirstName': None,
   'PrincipalLastName': None,
   'PrincipalPosition': None,
   'StateProvince': 'CA',
   'SubmittedName': None,
   'SubmittedOn': None,
   'SubmittedPosition': None,
   'VehicleTypes': []},
  {'Address': '1800 Honda Dr',
   'Address2': None,
   'City': 'Lincoln',
   'ContactEmail': 'Unknown@unknown.com',
   'ContactFax': None,
   'ContactPhone': None,
   'Country': 'UNITED STATES (USA)',
   'DBAs': None,
   'EquipmentItems': [],
   'LastUpdated': '/Date(1441217590880-0400)/',
   'ManufacturerTypes': [],
   'Mfr_CommonName': 'Honda',
   'Mfr_ID': 989,
   'Mfr_Name': 'HONDA MFG., ALABAMA., LLC.',
   'OtherManufacturerDetails': 'Truck is another product.',
   'PostalCode': '35096',
   'PrimaryProduct': None,
   'PrincipalFirstName': 'Koichi Kondo',
   'PrincipalLastName': None,
   'PrincipalPosition': 'CEO',
   'StateProvince': 'AL',
   'SubmittedName': None,
   'SubmittedOn': None,
   'SubmittedPosition': None,
   'VehicleTypes': []},
  {'Address': '4700 Tottenham Road',
   'Address2': None,
   'City': 'Alliston',
   'ContactEmail': None,
   'ContactFax': None,
   'ContactPhone': None,
   'Country': 'CANADA',
   'DBAs': None,
   'EquipmentItems': [],
   'LastUpdated': '/Date(-2208970800000-0500)/',
   'ManufacturerTypes': [],
   'Mfr_CommonName': 'Honda',
   'Mfr_ID': 990,
   'Mfr_Name': 'HONDA OF CANADA MFG., INC.',
   'OtherManufacturerDetails': 'Truck is another product.',
   'PostalCode': ' L9R 1A2',
   'PrimaryProduct': None,
   'PrincipalFirstName': None,
   'PrincipalLastName': None,
   'PrincipalPosition': None,
   'StateProvince': 'Ontario',
   'SubmittedName': None,
   'SubmittedOn': None,
   'SubmittedPosition': None,
   'VehicleTypes': []},
  {'Address': ' North Building, Highworth Road',
   'Address2': ' South Marston',
   'City': 'Swindon',
   'ContactEmail': None,
   'ContactFax': None,
   'ContactPhone': None,
   'Country': 'UNITED KINGDOM (UK)',
   'DBAs': None,
   'EquipmentItems': [],
   'LastUpdated': '/Date(-2208970800000-0500)/',
   'ManufacturerTypes': [],
   'Mfr_CommonName': 'Honda',
   'Mfr_ID': 991,
   'Mfr_Name': 'HONDA OF THE U.K. MFG., LTD.',
   'OtherManufacturerDetails': None,
   'PostalCode': 'SN3 4TZ',
   'PrimaryProduct': None,
   'PrincipalFirstName': None,
   'PrincipalLastName': None,
   'PrincipalPosition': None,
   'StateProvince': 'Wiltshire ',
   'SubmittedName': None,
   'SubmittedOn': None,
   'SubmittedPosition': None,
   'VehicleTypes': []},
  {'Address': '7250 Corredor Industria ',
   'Address2': None,
   'City': 'El Salto',
   'ContactEmail': 'Unknown@unknown.com',
   'ContactFax': None,
   'ContactPhone': None,
   'Country': 'MEXICO',
   'DBAs': None,
   'EquipmentItems': [],
   'LastUpdated': '/Date(1441217522583-0400)/',
   'ManufacturerTypes': [],
   'Mfr_CommonName': 'Honda',
   'Mfr_ID': 992,
   'Mfr_Name': 'HONDA DE MEXICO',
   'OtherManufacturerDetails': None,
   'PostalCode': '45680',
   'PrimaryProduct': None,
   'PrincipalFirstName': 'Koichi Kondo',
   'PrincipalLastName': None,
   'PrincipalPosition': 'CEO',
   'StateProvince': 'Jalisco',
   'SubmittedName': None,
   'SubmittedOn': None,
   'SubmittedPosition': None,
   'VehicleTypes': []},
  {'Address': '2755 North Michigan Avenue',
   'Address2': None,
   'City': 'Greensburg',
   'ContactEmail': None,
   'ContactFax': None,
   'ContactPhone': None,
   'Country': 'UNITED STATES (USA)',
   'DBAs': None,
   'EquipmentItems': [],
   'LastUpdated': '/Date(-2208970800000-0500)/',
   'ManufacturerTypes': [],
   'Mfr_CommonName': 'Honda',
   'Mfr_ID': 993,
   'Mfr_Name': 'HONDA MFG., INDIANA., LLC.',
   'OtherManufacturerDetails': 'Civic Sedan, Civic Natural Gas, Civic Hybrid',
   'PostalCode': '47240-9341',
   'PrimaryProduct': None,
   'PrincipalFirstName': None,
   'PrincipalLastName': None,
   'PrincipalPosition': None,
   'StateProvince': 'IN',
   'SubmittedName': None,
   'SubmittedOn': None,
   'SubmittedPosition': None,
   'VehicleTypes': []},
  {'Address': '1919 Torrance Blvd.',
   'Address2': None,
   'City': 'Torrance',
   'ContactEmail': 'john_turley@ahm.honda.com',
   'ContactFax': None,
   'ContactPhone': '(310)783-3276',
   'Country': 'UNITED STATES (USA)',
   'DBAs': None,
   'EquipmentItems': [],
   'LastUpdated': '/Date(1573736769243-0500)/',
   'ManufacturerTypes': [{'Name': 'Completed Vehicle Manufacturer'}],
   'Mfr_CommonName': 'Honda',
   'Mfr_ID': 1154,
   'Mfr_Name': 'AMERICAN HONDA MOTOR CO., INC.',
   'OtherManufacturerDetails': None,
   'PostalCode': '90501',
   'PrimaryProduct': None,
   'PrincipalFirstName': 'Shinji Aoyama',
   'PrincipalLastName': None,
   'PrincipalPosition': 'President and CEO',
   'StateProvince': 'California',
   'SubmittedName': 'John Turley',
   'SubmittedOn': '/Date(1573607278543-0500)/',
   'SubmittedPosition': 'Senior Manager, Product Regulatory Office',
   'VehicleTypes': [{'GVWRFrom': None,
     'GVWRTo': None,
     'IsPrimary': False,
     'Name': 'Motorcycle'},
    {'GVWRFrom': None,
     'GVWRTo': None,
     'IsPrimary': True,
     'Name': 'Passenger Car'},
    {'GVWRFrom': 'Class 2E: 6,001 - 7,000 lb (2,722 - 3,175 kg)',
     'GVWRTo': 'Class 2E: 6,001 - 7,000 lb (2,722 - 3,175 kg)',
     'IsPrimary': False,
     'Name': 'Truck '},
    {'GVWRFrom': 'Class 1B: 3,001 - 4,000 lb (1,360 - 1,814 kg)',
     'GVWRTo': 'Class 2E: 6,001 - 7,000 lb (2,722 - 3,175 kg)',
     'IsPrimary': False,
     'Name': 'Multipurpose Passenger Vehicle (MPV)'}]},
  {'Address': '410 Ladkrabang Industrial Estate',
   'Address2': 'Chalongkrung RoadLamplatue',
   'City': 'Ladkrabang',
   'ContactEmail': None,
   'ContactFax': None,
   'ContactPhone': '(310)783-3632',
   'Country': 'THAILAND',
   'DBAs': None,
   'EquipmentItems': [],
   'LastUpdated': '/Date(1467297434650-0400)/',
   'ManufacturerTypes': [],
   'Mfr_CommonName': None,
   'Mfr_ID': 14337,
   'Mfr_Name': 'THAI HONDA MANUFACTURING CO., LTD.',
   'OtherManufacturerDetails': None,
   'PostalCode': '10520',
   'PrimaryProduct': None,
   'PrincipalFirstName': 'Shunichi Eguchi',
   'PrincipalLastName': None,
   'PrincipalPosition': 'President',
   'StateProvince': 'Bangkok',
   'SubmittedName': 'JAY JOSEPH',
   'SubmittedOn': '/Date(1292562000000-0500)/',
   'SubmittedPosition': 'SENIOR MANAGER',
   'VehicleTypes': [{'GVWRFrom': 'Class 1A: 3,000 lb or less (1,360 kg or less)',
     'GVWRTo': 'Class 1A: 3,000 lb or less (1,360 kg or less)',
     'IsPrimary': True,
     'Name': 'Motorcycle'}]},
  {'Address': 'Phuc Thang ward',
   'Address2': None,
   'City': 'Phuc Yen town',
   'ContactEmail': None,
   'ContactFax': None,
   'ContactPhone': None,
   'Country': 'VIETNAM',
   'DBAs': None,
   'EquipmentItems': [],
   'LastUpdated': '/Date(1456836335247-0500)/',
   'ManufacturerTypes': [],
   'Mfr_CommonName': None,
   'Mfr_ID': 14691,
   'Mfr_Name': 'HONDA VIETNAM CO., LTD.',
   'OtherManufacturerDetails': None,
   'PostalCode': None,
   'PrimaryProduct': None,
   'PrincipalFirstName': 'Masayuki Igarashi',
   'PrincipalLastName': None,
   'PrincipalPosition': 'General Director',
   'StateProvince': 'Vinh Phuc province',
   'SubmittedName': None,
   'SubmittedOn': None,
   'SubmittedPosition': None,
   'VehicleTypes': []},
  {'Address': 'Rua Jurua, 160 - Dist.',
   'Address2': 'Industrial Marechal Castelo Branco - C.P.324',
   'City': None,
   'ContactEmail': None,
   'ContactFax': None,
   'ContactPhone': None,
   'Country': 'BRAZIL',
   'DBAs': None,
   'EquipmentItems': [],
   'LastUpdated': '/Date(1457627948787-0500)/',
   'ManufacturerTypes': [],
   'Mfr_CommonName': None,
   'Mfr_ID': 14782,
   'Mfr_Name': 'MOTO HONDA DA AMAZONIA LTDA.',
   'OtherManufacturerDetails': None,
   'PostalCode': None,
   'PrimaryProduct': None,
   'PrincipalFirstName': 'Issao Mizoguchi',
   'PrincipalLastName': None,
   'PrincipalPosition': 'President',
   'StateProvince': 'Manaus-AM-CEP 69075120',
   'SubmittedName': None,
   'SubmittedOn': None,
   'SubmittedPosition': None,
   'VehicleTypes': []},
  {'Address': 'No. 118 Jiasong Middle Road',
   'Address2': None,
   'City': 'Qingpu Shanghai',
   'ContactEmail': None,
   'ContactFax': None,
   'ContactPhone': None,
   'Country': 'CHINA',
   'DBAs': None,
   'EquipmentItems': [],
   'LastUpdated': '/Date(1509646743520-0400)/',
   'ManufacturerTypes': [],
   'Mfr_CommonName': 'Honda',
   'Mfr_ID': 14790,
   'Mfr_Name': 'SUNDIRO HONDA MOTORCYCLE CO., LTD.',
   'OtherManufacturerDetails': None,
   'PostalCode': '107-8556',
   'PrimaryProduct': None,
   'PrincipalFirstName': 'Kobayashi Taro',
   'PrincipalLastName': None,
   'PrincipalPosition': 'President',
   'StateProvince': 'Huaxin',
   'SubmittedName': None,
   'SubmittedOn': None,
   'SubmittedPosition': None,
   'VehicleTypes': []},
  {'Address': 'Carrer Del Mar Del Nord1-Poligono Indust. Can Roca La Torre Del Rector Santa',
   'Address2': 'Perpetua De Mogoda ',
   'City': 'Barcelona ',
   'ContactEmail': None,
   'ContactFax': None,
   'ContactPhone': None,
   'Country': 'SPAIN',
   'DBAs': None,
   'EquipmentItems': [],
   'LastUpdated': '/Date(1509646828663-0400)/',
   'ManufacturerTypes': [],
   'Mfr_CommonName': 'Montesa Honda',
   'Mfr_ID': 15171,
   'Mfr_Name': 'MONTESA HONDA SA',
   'OtherManufacturerDetails': None,
   'PostalCode': '08130',
   'PrimaryProduct': None,
   'PrincipalFirstName': None,
   'PrincipalLastName': None,
   'PrincipalPosition': None,
   'StateProvince': None,
   'SubmittedName': None,
   'SubmittedOn': None,
   'SubmittedPosition': None,
   'VehicleTypes': []}]}